DROP TABLE IF EXISTS URI_ROLE CASCADE;
DROP TABLE IF EXISTS URI CASCADE;
DROP TABLE IF EXISTS ROLE_ CASCADE;

CREATE TABLE URI
(
    URI_ID             BIGINT AUTO_INCREMENT,
    URI_NAME           VARCHAR(255) NOT NULL,
    URI_ORDER          INTEGER      NOT NULL,
    CREATED_DATE       TIMESTAMP    NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP    NOT NULL,
    CREATED_BY         VARCHAR(255) NOT NULL,
    LAST_MODIFIED_BY   VARCHAR(255) NOT NULL,
    CONSTRAINT URI_PK PRIMARY KEY (URI_ID),
    CONSTRAINT URI_UK_01 UNIQUE (URI_NAME)
);

CREATE TABLE ROLE_
(
    ROLE_ID            BIGINT AUTO_INCREMENT,
    ROLE_NAME          VARCHAR(255) NOT NULL,
    DESCRIPTION        VARCHAR(255),
    PARENT_ID          BIGINT,
    CREATED_DATE       TIMESTAMP    NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP    NOT NULL,
    CREATED_BY         VARCHAR(255) NOT NULL,
    LAST_MODIFIED_BY   VARCHAR(255) NOT NULL,
    CONSTRAINT ROLE_PK PRIMARY KEY (ROLE_ID),
    CONSTRAINT ROLE_UK_01 UNIQUE (ROLE_NAME),
    CONSTRAINT ROLE_FK_01 FOREIGN KEY (PARENT_ID) REFERENCES ROLE_ (ROLE_ID) ON DELETE SET NULL ON UPDATE RESTRICT
);

CREATE TABLE URI_ROLE
(
    URI_ROLE_ID        BIGINT AUTO_INCREMENT,
    URI_ID             BIGINT       NOT NULL,
    ROLE_ID            BIGINT       NOT NULL,
    CREATED_DATE       TIMESTAMP    NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP    NOT NULL,
    CREATED_BY         VARCHAR(255) NOT NULL,
    LAST_MODIFIED_BY   VARCHAR(255) NOT NULL,
    CONSTRAINT URI_ROLE_PK PRIMARY KEY (URI_ROLE_ID),
    CONSTRAINT URI_ROLE_UK_01 UNIQUE (URI_ID, ROLE_ID),
    CONSTRAINT URI_ROLE_FK_01 FOREIGN KEY (URI_ID) REFERENCES URI (URI_ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT URI_ROLE_FK_02 FOREIGN KEY (ROLE_ID) REFERENCES ROLE_ (ROLE_ID) ON DELETE CASCADE ON UPDATE RESTRICT
);

