DROP TABLE IF EXISTS ROLE_ CASCADE;

CREATE TABLE ROLE_
(
    ROLE_ID            BIGINT AUTO_INCREMENT,
    ROLE_NAME          VARCHAR(255) NOT NULL,
    DESCRIPTION        VARCHAR(255),
    PARENT_ID          BIGINT,
    CREATED_DATE       TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP,
    CREATED_BY         VARCHAR(255),
    LAST_MODIFIED_BY   VARCHAR(255),
    CONSTRAINT ROLE_PK PRIMARY KEY (ROLE_ID),
    CONSTRAINT ROLE_UK_01 UNIQUE (ROLE_NAME),
    CONSTRAINT ROLE_FK_01 FOREIGN KEY (PARENT_ID) REFERENCES ROLE_ (ROLE_ID) ON DELETE SET NULL ON UPDATE RESTRICT
);
