DROP TABLE IF EXISTS ROLE_ CASCADE;

CREATE TABLE ROLE_
(
    ROLE_ID            BIGINT AUTO_INCREMENT,
    ROLE_NAME          VARCHAR(255) NOT NULL,
    DESCRIPTION        VARCHAR(255),
    PARENT_ID          BIGINT,
    CREATED_DATE       TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP,
    CREATED_BY         VARCHAR(255),
    LAST_MODIFIED_BY   VARCHAR(255),
    CONSTRAINT ROLE_PK PRIMARY KEY (ROLE_ID),
    CONSTRAINT ROLE_UK_01 UNIQUE (ROLE_NAME),
    CONSTRAINT ROLE_FK_01 FOREIGN KEY (PARENT_ID) REFERENCES ROLE_ (ROLE_ID) ON DELETE SET NULL ON UPDATE RESTRICT
);

CREATE UNIQUE INDEX IU_ROLE_01 ON ROLE_ (ROLE_NAME);
CREATE INDEX IX_ROLE_02 ON ROLE_ (PARENT_ID);

insert into ROLE_ (ROLE_NAME, DESCRIPTION, PARENT_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATED_BY, LAST_MODIFIED_BY)
values ('ROLE_ADMIN', '관리자 권한', null, now(), now(), 'system', 'system');
insert into ROLE_ (ROLE_NAME, DESCRIPTION, PARENT_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATED_BY, LAST_MODIFIED_BY)
values ('ROLE_MANAGER', '매니저 권한', 1, now(), now(), 'system', 'system');
insert into ROLE_ (ROLE_NAME, DESCRIPTION, PARENT_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATED_BY, LAST_MODIFIED_BY)
values ('ROLE_VIP', '특급 권한', 2, now(), now(), 'system', 'system');
insert into ROLE_ (ROLE_NAME, DESCRIPTION, PARENT_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATED_BY, LAST_MODIFIED_BY)
values ('ROLE_USER', '유저 권한', 3, now(), now(), 'system', 'system');
