DROP TABLE IF EXISTS USER_ CASCADE;
DROP TABLE IF EXISTS ROLE_ CASCADE;

CREATE TABLE ROLE_
(
    ROLE_ID            BIGINT AUTO_INCREMENT,
    ROLE_NAME          VARCHAR(255) NOT NULL,
    DESCRIPTION        VARCHAR(255),
    PARENT_ID          BIGINT,
    CREATED_DATE       TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP,
    CREATED_BY         VARCHAR(255),
    LAST_MODIFIED_BY   VARCHAR(255),
    CONSTRAINT ROLE_PK PRIMARY KEY (ROLE_ID),
    CONSTRAINT ROLE_UK_01 UNIQUE (ROLE_NAME),
    CONSTRAINT ROLE_FK_01 FOREIGN KEY (PARENT_ID) REFERENCES ROLE_ (ROLE_ID) ON DELETE SET NULL ON UPDATE RESTRICT
);

CREATE TABLE USER_
(
    USER_ID            BIGINT AUTO_INCREMENT,
    USERNAME           VARCHAR(255) NOT NULL,
    NICKNAME           VARCHAR(255) NOT NULL,
    PASSWORD           VARCHAR(255) NOT NULL,
    ROLE_ID            BIGINT       NOT NULL,
    CREATED_DATE       TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP,
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
    CONSTRAINT USER_UK_01 UNIQUE (USERNAME),
    CONSTRAINT USER_FK_01 FOREIGN KEY (ROLE_ID) REFERENCES ROLE_ (ROLE_ID) ON DELETE SET NULL ON UPDATE RESTRICT
);

insert into ROLE_ (ROLE_NAME, DESCRIPTION, PARENT_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATED_BY, LAST_MODIFIED_BY)
values ('ROLE_ADMIN', '관리자 권한', null, now(), now(), 'system', 'system');
insert into ROLE_ (ROLE_NAME, DESCRIPTION, PARENT_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATED_BY, LAST_MODIFIED_BY)
values ('ROLE_MANAGER', '매니저 권한', 1, now(), now(), 'system', 'system');
insert into ROLE_ (ROLE_NAME, DESCRIPTION, PARENT_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATED_BY, LAST_MODIFIED_BY)
values ('ROLE_VIP', '특급 권한', 2, now(), now(), 'system', 'system');
insert into ROLE_ (ROLE_NAME, DESCRIPTION, PARENT_ID, CREATED_DATE, LAST_MODIFIED_DATE, CREATED_BY, LAST_MODIFIED_BY)
values ('ROLE_USER', '유저 권한', 3, now(), now(), 'system', 'system');

insert into USER_ (USERNAME, NICKNAME, PASSWORD, ROLE_ID, CREATED_DATE, LAST_MODIFIED_DATE)
values ('user01', '관리자', '1234', 1, now(), now());
insert into USER_ (USERNAME, NICKNAME, PASSWORD, ROLE_ID, CREATED_DATE, LAST_MODIFIED_DATE)
values ('user02', '매니저', '1234', 2, now(), now());
insert into USER_ (USERNAME, NICKNAME, PASSWORD, ROLE_ID, CREATED_DATE, LAST_MODIFIED_DATE)
values ('user03', '특', '1234', 3, now(), now());
insert into USER_ (USERNAME, NICKNAME, PASSWORD, ROLE_ID, CREATED_DATE, LAST_MODIFIED_DATE)
values ('user04', '유저', '1234', 4, now(), now());
insert into USER_ (USERNAME, NICKNAME, PASSWORD, ROLE_ID, CREATED_DATE, LAST_MODIFIED_DATE)
values ('user05', '익명', '1234', null, now(), now());
